In [ ]:


import pandas as pd

In [ ]:
df = pd.read_csv('dataset.csv', encoding='latin1')

In [ ]:
df.sample() #filas aleatorias

,Unnamed: 0,Nro de documento,Nombre y Apellido,Matemática,Física,Programación,Lengua,Estadística,Programacion,Historia y Geografia,Castellano,Educacion etica y ciudadana,Geometria
8,NaN,18753159,Javier Ruiz,3,2,4,3,3,3,4,3,3,3

In [ ]:
df.shape #cantidad de filas, columnas)

(10, 13)

In [ ]:
df.columns #nombres de columnas

Index(['Unnamed: 0', 'Nro de documento', 'Nombre y Apellido', 'Matemática',
       'Física', 'Programación', 'Lengua', 'Estadística', 'Programacion',
       'Historia y Geografia', 'Castellano', 'Educacion etica y ciudadana',
       'Geometria'],
      dtype='object')

In [ ]:
df.info() #tipos de datos nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   0 non-null      float64
 1   Nro de documento             10 non-null     int64
 2   Nombre y Apellido            10 non-null     object
 3   Matemática                   10 non-null     int64
 4   Física                       10 non-null     int64
 5   Programación                 10 non-null     int64
 6   Lengua                       10 non-null     int64
 7   Estadística                  10 non-null     int64
 8   Programacion                 10 non-null     int64
 9   Historia y Geografia         10 non-null     int64
 10  Castellano                   10 non-null     int64
 11  Educacion etica y ciudadana  10 non-null     int64
 12  Geometria                    10 non-null     int64
dtypes: float64(1), int64(11), object(1)
memory usage: 1.1+ KB

In [ ]:
df.describe() #estadisticas (numericas)

,Unnamed: 0,Nro de documento,Matemática,Física,Programación,Lengua,Estadística,Programacion,Historia y Geografia,Castellano,Educacion etica y ciudadana,Geometria
count,0.0,1.000000e+01,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,NaN,1.501719e+07,3.400000,3.300000,3.800000,3.800000,3.500000,3.600000,4.000000,4.000000,3.700000,3.400000
std,NaN,3.058530e+06,1.429841,1.494434,1.032796,1.032796,1.433721,1.505545,0.942809,0.942809,1.159502,1.429841
min,NaN,1.023457e+07,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,3.000000,2.000000,1.000000
25%,NaN,1.267301e+07,2.250000,2.000000,3.000000,3.000000,2.250000,2.250000,4.000000,3.000000,3.000000,2.250000
50%,NaN,1.496814e+07,3.500000,3.500000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.500000
75%,NaN,1.711048e+07,4.750000,4.750000,4.750000,4.750000,4.750000,5.000000,4.750000,5.000000,4.750000,4.750000
max,NaN,1.945612e+07,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
df.describe(include='all')

,Unnamed: 0,Nro de documento,Nombre y Apellido,Matemática,Física,Programación,Lengua,Estadística,Programacion,Historia y Geografia,Castellano,Educacion etica y ciudadana,Geometria
count,0.0,1.000000e+01,10,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
unique,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Juan Pérez,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.501719e+07,NaN,3.400000,3.300000,3.800000,3.800000,3.500000,3.600000,4.000000,4.000000,3.700000,3.400000
std,NaN,3.058530e+06,NaN,1.429841,1.494434,1.032796,1.032796,1.433721,1.505545,0.942809,0.942809,1.159502,1.429841
min,NaN,1.023457e+07,NaN,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000,3.000000,2.000000,1.000000
25%,NaN,1.267301e+07,NaN,2.250000,2.000000,3.000000,3.000000,2.250000,2.250000,4.000000,3.000000,3.000000,2.250000
50%,NaN,1.496814e+07,NaN,3.500000,3.500000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.500000
75%,NaN,1.711048e+07,NaN,4.750000,4.750000,4.750000,4.750000,4.750000,5.000000,4.750000,5.000000,4.750000,4.750000
max,NaN,1.945612e+07,NaN,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [ ]:
df.isnull().sum()

Unnamed: 0                     10
Nro de documento                0
Nombre y Apellido               0
Matemática                      0
Física                          0
Programación                    0
Lengua                          0
Estadística                     0
Programacion                    0
Historia y Geografia            0
Castellano                      0
Educacion etica y ciudadana     0
Geometria                       0
dtype: int64

sample_data